### ISSUE TITLE
"Unknown part workbench.parts.activitybar" when moving to the sidebar!

### ISSUE THREAD

**Issue by a-eid** [getcursor/cursor#1570]
1) If you can, please include a screenshot of your problem

![Screenshot 2024-07-26 at 10 28 21 PM](https://github.com/user-attachments/assets/8d4efa36-b505-4d9b-97a1-84302d8777d5)

2) Please include the name of your operating system
MacOS

3) If you can, steps to reproduce are super helpful

I have these shortcuts to move between splits ( ctrl + l ) to move to right right split & ( ctrl + h ) to move to the left split.

**Comment by washanhanzi** [comment]
Got the same problem, the action is `workbench.action.navigateLeft` and similar ones.

**Comment by Bubbleinpit** [comment]
Same problem here. I just want to use keybinding to navigate among panels but I always get this error message.

```
[
  {
    "key": "ctrl+j",
    "command": "workbench.action.navigateDown"
  },
  {
    "key": "ctrl+k",
    "command": "workbench.action.navigateUp"
  },
  {
    "key": "ctrl+h",
    "command": "workbench.action.navigateLeft"
  },
  {
    "key": "ctrl+l",
    "command": "workbench.action.navigateRight"
  }
]
```

**Comment by benschac** [comment]
SAME!

**Comment by code661** [comment]
This way it can be solved.

`"workbench.activityBar.orientation": "vertical",`

![CleanShot 2024-08-28 at 10 56 28@2x](https://github.com/user-attachments/assets/70ebb865-b1e4-4e4c-90b7-9c7252bb3ded)

**Comment by yangsimin** [comment]
> This way it can be solved.
> 
> `"workbench.activityBar.orientation": "vertical",`
> 
> ![CleanShot 2024-08-28 at 10 56 28@2x](https://private-user-images.githubusercontent.com/19431743/362103628-70ebb865-b1e4-4e4c-90b7-9c7252bb3ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTU3MDQsIm5iZiI6MTcyNDgxNTQwNCwicGF0aCI6Ii8xOTQzMTc0My8zNjIxMDM2MjgtNzBlYmI4NjUtYjFlNC00ZTRjLTkwYjctOWM3MjUyYmIzZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MGI4YjhkOTg0YWU4NTc5MjUwNDlkMjE2NmJjZmE2M2E2M2E1NTg1OWQwMGQ2M2JlMjlkNDcyYjc4NTI3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wu7bF9Fz3PckaKHztNw54B8qm5uugSbCgXD86OvW5sU)

It works !!

**Comment by yagudaev** [comment]
Thanks, @code661, it works great. Life saver 🛟

**Comment by coindegen** [comment]
> This way it can be solved.
> 
> `"workbench.activityBar.orientation": "vertical",`


you da real MVP 🏆🏆

**Comment by turfaa** [comment]
Thanks @code661, it works!

However I only can move from the editor to the sidebar using ctrl+h. I can't go from the sidebar to the editor using ctrl+l.

**Comment by mrjxtr** [comment]
> Thanks @code661, it works!
> 
> However I only can move from the editor to the sidebar using ctrl+h. I can't go from the sidebar to the editor using ctrl+l.
> 
> Edit: I just managed to do this by adding this in my `keybindings.json`:
> 
> ```json
>     {
>         "key":"ctrl+l",
>         "when":"sideBarFocus",
>         "command":"workbench.action.focusActiveEditorGroup"
>     }
> ```

So `ctrl-l` will only work when we are in the sidebar but how about when we are navigating between 2 editor groups next to each other?

**Comment by resetheadhard** [comment]
> So `ctrl-l` will only work when we are in the sidebar but how about when we are navigating between 2 editor groups next to each other?

Assuming you mean moving between the sidebar and a left and right group of editors, I have the same keybinding set as you mention and can navigate back and forth between them all.

**Comment by alecgerona** [comment]
How do you navigate in/out of Chat/Compose window?

**Comment by saadfarooq07** [comment]
If you can’t do this you shouldn’t be coding

**Comment by dassongh** [comment]
<img width="317" alt="Image" src="https://github.com/user-attachments/assets/82b7c504-7dbd-44d6-a8b1-cb803d2e3028" />

"vertical" activity bar alignment is broken in recent update 🫠

**Comment by mrjxtr** [comment]
> "vertical" activity bar alignment is broken in recent update 🫠

You can create a separate issue for that

**Comment by mrjxtr** [comment]
> > So `ctrl-l` will only work when we are in the sidebar but how about when we are navigating between 2 editor groups next to each other?
> 
> Assuming you mean moving between the sidebar and a left and right group of editors, I have the same keybinding set as you mention and can navigate back and forth between them all.

If you are still having this issue... the fix is `  "workbench.activityBar.orientation": "vertical", // this is to fix the vim ctrl+l/h bug`

**Comment by Bubbleinpit** [comment]
> "vertical" activity bar alignment is broken in recent update 🫠

@dassongh You can use "Custom CSS and JS Loader" extension to configure custom CSS styles to restore it to the VSCode appearance:

```css
/** Restore the height of the activity bar element to the vscode default value */
.monaco-workbench .composite-bar .monaco-action-bar:not(.vertical) .action-item {
  height: 35px !important;
}

/** Restore the icon size of the activity bar element to the vscode default value */
.monaco-workbench .composite-bar .monaco-action-bar .action-item .action-label {
  font-size: 16px !important;
}

/** Restore the progress icon position of the activity bar element to the vscode default value */
.monaco-workbench .progress-badge>.badge-content:before {
  transform: none !important;
  left: 1px !important;
  top: 1px !important;
}
```
